#Site wide configuration
title: Junior QA Engineer
icon: favicon.ico
locale: en_US

#Platform usernames
name: Maria Bezobiuk
author: Maria Bezobiuk
avatar: images\photo-bio.jpg
email: bezobiuk.mari@gmail.com
linkedin: mari-bezobiuk
description: Manual QA Engineer, Automation QA Engineer, Software Testing
github_username: Mari-Bezobiuk
show_excerpts: true
theme: jekyll-theme-leap-day
encoding: UTF-8

